import tinycolor, { type Instance } from 'tinycolor2';

const darkest = 10;
const lightest = 95;
const darkSteps = 4;
const lightSteps = 5;

const lightnessStep = (lightest - 50) / lightSteps;
const darknessStep = (50 - darkest) / darkSteps;

function setLightness(hsl: tinycolor.ColorFormats.HSLA, lightness: number) {
  hsl.l = lightness;
  return tinycolor(hsl).toHexString();
}

function gradientBySteps(baseColor: Instance) {
  const baseHsl = baseColor.toHsl();
  return [
    setLightness(baseHsl, 50 + lightnessStep * 5),
    setLightness(baseHsl, 50 + lightnessStep * 4),
    setLightness(baseHsl, 50 + lightnessStep * 3),
    setLightness(baseHsl, 50 + lightnessStep * 2),
    setLightness(baseHsl, 50 + lightnessStep),
    setLightness(baseHsl, 50),
    setLightness(baseHsl, 50 - darknessStep),
    setLightness(baseHsl, 50 - darknessStep * 2),
    setLightness(baseHsl, 50 - darknessStep * 3),
    setLightness(baseHsl, 50 - darknessStep * 4),
    setLightness(baseHsl, 50 - darknessStep * 5),
  ];
}

function gradientBySaturation(baseColor: Instance) {
  const baseHsl = baseColor.toHsl();

  // A more balanced lightness scale, inspired by modern design systems.
  const lightnessScale = [0.97, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1, 0.05];
  const colors: string[] = [];
  for (const l of lightnessScale) {
    const newHsl = { ...baseHsl };
    newHsl.l = l;

    // Dynamically adjust saturation for better aesthetics.
    // Lighter colors get desaturated to appear more pastel and less "neon".
    // Mid-range and darker colors retain more saturation for vibrancy.
    if (l > 0.8) {
      // Significantly reduce saturation for the lightest shades.
      newHsl.s *= 0.4;
    } else if (l > 0.6) {
      // Moderately reduce saturation for light shades.
      newHsl.s *= 0.8;
    } else if (l < 0.3) {
      // Slightly boost saturation for the darkest shades to prevent muddiness.
      newHsl.s = Math.min(1, newHsl.s * 1.1);
    }

    colors.push(tinycolor(newHsl).toHexString().toUpperCase());
  }
  return colors;
}

function gradinetByLightness(baseColor: Instance) {
  const colors: string[] = [];
  const lightnessSteps = [
    95,
    90,
    80,
    70,
    60, // Lighter shades
    50,
    40,
    30,
    20,
    10,
    5, // Darker shades
  ];

  for (const lightness of lightnessSteps) {
    const newHsl = baseColor.toHsl();
    newHsl.l = lightness / 100;
    colors.push(tinycolor(newHsl).toHexString().toUpperCase());
  }
  return colors;
}

/**
 * Generates a 10-shade color gradient from a base hexadecimal color.
 * The gradient is generated by adjusting the lightness in HSL color space.
 * @param baseHexColor - The base hexadecimal color (e.g., "#123456").
 * @param mode gradient production mode
 * @returns An array of 10 hex color strings representing the gradient, or null if invalid.
 */
export function generateColorGradient(
  baseHexColor: string,
  mode: string = 'base',
): string[] | null {
  const baseColor = tinycolor(baseHexColor);
  if (!baseColor.isValid()) {
    console.error('Invalid base hex color provided.');
    return null;
  }
  switch (mode) {
    case 'saturation':
      return gradientBySaturation(baseColor);
    case 'lightness':
      return gradinetByLightness(baseColor);
    default:
      return gradientBySteps(baseColor);
  }
}

export function themeWA(
  baseColorHex = '#087f5b', // A teal color
  variant: string,
  name = 'custom',
  selector: string = ':root',
  palette: string = 'base',
) {
  const gradient = generateColorGradient(baseColorHex, palette);

  if (!gradient) return '';

  // language=css
  return `
    ${selector},
    ${selector}.wa-light,
    ${selector}.wa-dark .wa-invert {
      --mov-color-${name}-95: ${gradient[0]};
      --mov-color-${name}-90: ${gradient[1]};
      --mov-color-${name}-80: ${gradient[2]};
      --mov-color-${name}-70: ${gradient[3]};
      --mov-color-${name}-60: ${gradient[4]};
      --mov-color-${name}-50: ${gradient[5]};
      --mov-color-${name}-40: ${gradient[6]};
      --mov-color-${name}-30: ${gradient[7]};
      --mov-color-${name}-20: ${gradient[8]};
      --mov-color-${name}-10: ${gradient[9]};
      --mov-color-${name}-05: ${gradient[10]};
      --mov-color-${name}: var(--mov-color-${name}-60);
      --mov-color-${name}-key: 60;
      --mov-color-${name}-gte-60: calc(100% - (clamp(0, 60 - var(--mov-color-${name}-key), 1) * 100%));
      --mov-color-${name}-on: color-mix(in oklab, var(--mov-color-${name}-10) var(--mov-color-${name}-gte-60), white);

      --wa-color-${variant}-95: var(--mov-color-${name}-95);
      --wa-color-${variant}-90: var(--mov-color-${name}-90);
      --wa-color-${variant}-80: var(--mov-color-${name}-80);
      --wa-color-${variant}-70: var(--mov-color-${name}-70);
      --wa-color-${variant}-60: var(--mov-color-${name}-60);
      --wa-color-${variant}-50: var(--mov-color-${name}-50);
      --wa-color-${variant}-40: var(--mov-color-${name}-40);
      --wa-color-${variant}-30: var(--mov-color-${name}-30);
      --wa-color-${variant}-20: var(--mov-color-${name}-20);
      --wa-color-${variant}-10: var(--mov-color-${name}-10);
      --wa-color-${variant}-05: var(--mov-color-${name}-05);
      --wa-color-${variant}: var(--mov-color-${name});
      --wa-color-${variant}-on: var(--mov-color-${name}-on);


        /*--wa-color-surface-lowered: var(--wa-color-${variant}-95);*/
        /*--wa-color-surface-border: var(--wa-color-${variant}-90);*/

        /*--wa-color-text-normal: var(--wa-color-${variant}-10);*/
        /*--wa-color-text-quiet: var(--wa-color-${variant}-40);*/

        /*--wa-color-overlay-modal: color-mix(in oklab, var(--wa-color-${variant}-05) 50%, transparent);*/
        /*--wa-color-overlay-inline: color-mix(in oklab, var(--wa-color-${variant}-80) 25%, transparent);*/

        /*--wa-color-shadow: color-mix(in oklab, var(--wa-color-${variant}-05) calc(var(--wa-shadow-blur-scale) * 4% + 8%), transparent);*/

      --wa-color-${variant}-fill-quiet: var(--wa-color-${variant}-95);
      --wa-color-${variant}-fill-normal: var(--wa-color-${variant}-90);
      --wa-color-${variant}-fill-loud: var(--wa-color-${variant}-20);
      --wa-color-${variant}-border-quiet: var(--wa-color-${variant}-90);
      --wa-color-${variant}-border-normal: var(--wa-color-${variant}-80);
      --wa-color-${variant}-border-loud: var(--wa-color-${variant}-60);
      --wa-color-${variant}-on-quiet: var(--wa-color-${variant}-40);
      --wa-color-${variant}-on-normal: var(--wa-color-${variant}-30);
      --wa-color-${variant}-on-loud: white;

    }

    ${selector}.wa-dark,
    ${selector}.wa-light .wa-invert {
        /*--wa-color-surface-raised: var(--wa-color-${variant}-10);*/
        /*--wa-color-surface-default: var(--wa-color-${variant}-05);*/

        /*--wa-color-surface-border: var(--wa-color-${variant}-20);*/

        /*--wa-color-text-normal: var(--wa-color-${variant}-95);*/
        /*--wa-color-text-quiet: var(--wa-color-${variant}-60);*/

        /*--wa-color-overlay-inline: color-mix(in oklab, var(--wa-color-${variant}-50) 10%, transparent);*/

      --wa-color-${variant}-fill-quiet: var(--wa-color-${variant}-10);
      --wa-color-${variant}-fill-normal: var(--wa-color-${variant}-20);
      --wa-color-${variant}-fill-loud: var(--wa-color-${variant}-90);
      --wa-color-${variant}-border-quiet: var(--wa-color-${variant}-20);
      --wa-color-${variant}-border-normal: var(--wa-color-${variant}-30);
      --wa-color-${variant}-border-loud: var(--wa-color-${variant}-40);
      --wa-color-${variant}-on-quiet: var(--wa-color-${variant}-60);
      --wa-color-${variant}-on-normal: var(--wa-color-${variant}-70);
      --wa-color-${variant}-on-loud: var(--wa-color-${variant}-05);
    }
  `;
}
